### ISSUE TITLE
No documentation on the essentails.exempt permission shown 

### ISSUE THREAD

**Issue by E-Gostlow** [Xeyame/essinfo.xeya.me#18]
There are no results for the essentials.exempt permission node shown in luckperms.

![image](https://user-images.githubusercontent.com/62462110/121807938-2aa67700-cc4e-11eb-8366-361554772d3b.png)

**Comment by Xeyame** [comment]
Hello, please open an issue at the essentialsx github page for this issue. The permission results shown in luckperms are fetched from the data provided by the essentialsx plugin, not by this website.
