### ISSUE TITLE
essentials.itemlore.<effect> not listed

### ISSUE THREAD

**Issue by chrisraj1** [Xeyame/essinfo.xeya.me#19]
essentials.itemlore.\<effect> is not listed even though it exists. I know this because I gave the permission essentials.itemlore.* and it allowed me to use color codes in my lore. Not sure if essentials.itemlore.prevent-type.<material_name> is also a permission that needs to defined, but I would assume so as itemname also has that node.

Both essentials.itemlore and essentials.itemname stop autofill within LP at those points. I sort of had to guess with essentials.itemlore.*

**Comment by ToonTown0909** [comment]
To make sure I understand, your concern is that the permissions node `essentials.itemlore` is not on the list? Or that there are additional, sub-permissions in EssX that are not listed? I'm happy to implement changes though I'm unclear on what, specifically, you are requesting be adjusted.

**Comment by ToonTown0909** [comment]
This issue is being closed due to no response from the client. The client may submit resubmit their concern as a new issue if they wish.
