### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by GTOL** [Xeyame/essinfo.xeya.me#2]
1. **essentials.signs.*** permissions belong to **Essentials** but not **EssentialsProtect** module.
2. I cannot find **essentials.protect**, **essentials.protect.admin** and **essentials.protect.ownerinfo** permissions in the source code. Please review those permissions.

**Comment by Xeyame** [comment]
Hmm, It looks like the essentials.protect.admin is left over from https://github.com/EssentialsX/Essentials/commit/76ba31d1a3ca54ffe78b9a63c80d1f6080cea688 and with a description from some other random place. I'm removing it soon, also fixing the signs module name. Thanks for notifying me!

**Comment by GTOL** [comment]
I think all those three permissions (ess.protect, ess.protect.admin and ess.protect.ownerinfo) were completely removed in the version 2.11.1 after this [commit](https://github.com/EssentialsX/Essentials/commit/8d77a3f941606f01b8aa63651a28fd3a127360ed#diff-1fede799f073df32c5c4f0a34da6fbb5). 
You should also remove **essentials.protect** and **essentials.protect.ownerinfo**

**Comment by Xeyame** [comment]
Yea, currently I'm not home so I can't fix it, but I already discussed this earlier today with other people but they weren't really sure too, looking into the code soon (tm)

**Comment by Xeyame** [comment]
Fixed in https://github.com/Xeyame/essinfo.xeya.me/commit/c17f15c7ce3c39e29859201d256b8aa12df2740f, Please reopen or reply to this issue or create a new one if you find more inconsistent things, Thanks!!
