### ISSUE TITLE
essentials.jail.notify

### ISSUE THREAD

**Issue by LaxWasHere** [Xeyame/essinfo.xeya.me#22]
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandtogglejail.java#L91

**Comment by ToonTown0909** [comment]
Will look at this now. Please standby.

**Comment by ToonTown0909** [comment]
Permission `essentials.jail.notify` has been added.

Please see: https://github.com/Xeyame/essinfo.xeya.me/pull/23
