### ISSUE TITLE
Incorrect permissions documentation for banip notifications

### ISSUE THREAD

**Issue by TheBentoBox** [Xeyame/essinfo.xeya.me#6]
As you can see here, the docs state that banip notifications will be sent to players with the `essentials.ban.notify` permission:
![image](https://user-images.githubusercontent.com/6902229/81493386-d2d05c00-9254-11ea-8331-4727b47df64e.png)

However, the plugin actually checks for the `essentials.banip.notify` permission to send IP ban notifications, [see here](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandbanip.java#L65).

**Comment by Xeyame** [comment]
Thanks!
